//
export const ADD_DEPTH_STATE = "ADD_DEPTH_STATE"
export const ADD_MARKET_ACTION = "ADD_MARKET_ACTION"
export const ADD_MARKET_STATE_PRICE = "ADD_MARKET_STATE_PRICE"
export const ADD_MARKET_STATE_TEXT = "ADD_MARKET_STATE_TEXT"
