//
export const ADD_DEPTH_STATE = "ADD_DEPTH_STATE"
export const ADD_MARKET_ACTION = "ADD_MARKET_ACTION"
export const ADD_MARKET_STATE_PRICE = "ADD_MARKET_STATE_PRICE"
export const ADD_MARKET_STATE_TEXT = "ADD_MARKET_STATE_TEXT"
export const ADD_MARKET_FACT_QUALITATIVE = "ADD_MARKET_FACT_QUALITATIVE"
export const ADD_MARKET_FACT_QUANTITATIVE = "ADD_MARKET_FACT_QUANTITATIVE"
export const ADD_PREDICTION_PERFORMANCE = "ADD_PREDICTION_PERFORMANCE"